name: NoXPDropsPlugin
version: '${project.version}'
main: tsa.noxpdropsplugin.NoXPDropsPlugin
api-version: 1.20

commands:
  skulk:
    permission: noxpdrops.use
  skulkinfo:
    permission: noxpdrops.use